### ISSUE TITLE
how i can add country list from dblist

### ISSUE THREAD

**Issue by kacedali** [QoboLtd/project-template-cakephp#275]
i dont understand how its work
for users i wanted to add country list from database list but nothing happend :(

**Comment by mamchenkov** [comment]
Hi,

Users is a tricky module, as most of its functionality comes from CakeDC/Users.  I've just checked the source and it looks like we have something hardcoded in there, which probably should and can be improved (we'll look at it later).

For now, you can either create a CSV country list:

1. Create folder `config/Modules/Common/lists'
2. Create a file `countries.csv` in that foloder with the list of countries.

Here is an example of the countries list:

```
VALUE,LABEL,INACTIVE
GB,"United Kingdom"
US,"United States"
```

This should show the two countries in the dropdown of the user adding/editing forms.

Alternatively, you can update the views, to rely on the database list, rather than the CSV list.  You can do so by editing `src/Template/Plugin/CakeDC/Users/Users/add.ctp` and `src/Template/Plugin/CakeDC/Users/Users/edit.ctp`, and replacing `'type' => 'list(countries)'` with `'type' => 'dblist(countries)'` in there.  Not the most elegant solution, I know.

We'll look at the templates sometime this week to make sure they work fine in standalone setups.  We haven't noticed the issue as we do include `countries.csv` in our applications.

Thanks for the feedback!

**Comment by mamchenkov** [comment]
@kacedali check the PR #276 for the CSV (not Database List) solution to your problem.
