### ISSUE TITLE
SQL error issue

### ISSUE THREAD

**Issue by fr3nch13** [QoboLtd/project-template-cakephp#470]
First, I have to say, this base template is awesome! I was in the middle of doing something like this, you guys have done a great job of putting this together.

I wanted you guys to be aware of an issue I came across, that I was able to fix.

Stats:
Ubuntu: 16.0.4
Apache: 2.4
Mysql: 5.7.21
php: 7.0.25
cakephp: 3.5.12

It's an sql error involving joins. I have a default install of mysql. I was able to track it to the below overflow link. The suggested sql worked to fix it:

`mysql > SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

https://stackoverflow.com/questions/23921117/disable-only-full-group-by

![screen shot 2018-02-13 at 8 16 57 pm](https://user-images.githubusercontent.com/7828/36187745-2e6a800e-10fc-11e8-9eed-fccfbff7a6e1.png)

**Comment by mamchenkov** [comment]
@fr3nch13 

thanks for the feedback and the info!  Glad you found the template useful.

In regards to the SQL issue - yes, we have been experiencing some weird behaviors here and there with the newer version of MySQL (5.7 or so).  We'll add the "Known Issues" sections to the README with the suggestions on how to fix these, until we have something better.

Feel free to reach out if you need any information or suggestions on the template and related plugins.

**Comment by fr3nch13** [comment]
Btw, I’m a CakePHP 1.3 and 2.x guru, but a noob at CakePHP 3.x

-------------
Brian French
703-507-5383

**Comment by mamchenkov** [comment]
@fr3nch13 I've worked with CakePHP since the 1.x times pretty much non-stop.  CakePHP 3 is the best of them by far.  And 4.x is coming out soon, which brings a number of improvements.  Gladly, the transition from 3 to 4 will be much smoother than from 1 to 2 and from 2 to 3.

Exciting times ahead! :)

**Comment by fr3nch13** [comment]
2 to 3 is rough. For a few projects we have on 2 for the past four years, they’re almost impossible. 
I’m currently working on a personal project of mine that was running, and it’s basically easier to do a complete rewrite to 3. 

Hopefully 4 won’t be too crazy. 

-------------
Brian French
703-507-5383

**Comment by mamchenkov** [comment]
Yes, agreed.  For many projects it was easier and faster to rewrite from scratch, rather than migrate from 2 to 3.  CakePHP core team learned their lesson though.  This time around things will be much easier.  In the next minor release - 3.6 - CakePHP will start throwing deprecated warnings for everything that will disappear or break in 4.0.  Once those are fixed, everything will just work in CakePHP 4.

Have a look at the CakePHP roadmap here:

* https://github.com/cakephp/cakephp/wiki/3.6-Roadmap
* https://github.com/cakephp/cakephp/wiki/4.0-Roadmap

**Comment by fr3nch13** [comment]
So they’re not going to stab us that hard this time. I’ve been using CakePHP for over ten years now. And they really have built an amazing and mature framework. It still rivals Django/symphony/node imo. (Depending on what you’re making). 

-------------
Brian French
703-507-5383

**Comment by fr3nch13** [comment]
The app I’m moving is running on 1.3 to 3.x, so basically a rewrite. 

-------------
Brian French
703-507-5383

**Comment by mamchenkov** [comment]
@fr3nch13 once again, thanks for the info.  I have updated the README file with instructions on how to work around the issue.
